### ISSUE TITLE
Contact entity and address book interface

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#11]
Retrieving all the contacts from the user inbox and storing to DB.

**Comment by lukesmurray** [comment]
How do we define a contact? I think there are two ways of defining it here. One is simply an email address. The other is as someone you know. Some users want to be able to do something like get the most recent emails from the sender. This only requires contact to be an email address. On the other hand some people want to do something like if the email is not from my contacts then file it as low priority. In this case unless we are syncing with an address book we don't have a way of saying that someone is a contact. We could use heuristics for this like you sent them three emails so they are someone you know. However solely receiving an email from someone should not be enough to make them a contact in the sense that they are defined as someone you know.

**Comment by soyapark** [comment]
I think we should define contacts as your former suggestion. We should save every email address to gauge the 'relationship' with each person.  

I was thinking of going through entire email in a user's inbox when they first register to YoUPS and store every individual email address as a contact instance. And every time there is a new message, check the sender and recipient of the message and add new people as contact entities.

**Comment by lukesmurray** [comment]
As a result of our conversation today I now think `Contact` can have multiple email addresses associated with it which makes the mapping from email address to contact and vice versa slightly more complicated.
