### ISSUE TITLE
calendar function default param

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#137]
Ideally, the function should have a default value for its params i.e. `get_conflicts()` and `create_event()` requires at least one param value from users. 

Let's think about and go back to our survey results to find the most common use case for these functions and determine default values for params. For example, for get_conflicts(), the most user would be curious if I'm busy * now * (= when this email is triggered).

**Comment by dillzhang** [comment]
Added it for geet_conflicts() to be the current time plus an hour.

Cannot find a reasonable default for create_event().
