### ISSUE TITLE
403- Users can't login at some browser due to its security

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#18]
suggest trying a different browser?

![image](https://user-images.githubusercontent.com/33616044/53259507-3ea0c600-369d-11e9-9417-0d25cfad98fc.png)

**Comment by lukesmurray** [comment]
What we need is a certificate. The actual process for creating this wouldn't be hard https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-16-04 but I don't want to mess up the server by trying it.

**Comment by soyapark** [comment]
But deployment server is already on https. Is it different than the certificate you are talking about?

**Comment by lukesmurray** [comment]
Interesting what browser does this fail on? I logged in fine on chrome. We should also get a certificate for the dev server btw.

**Comment by soyapark** [comment]
@dillzhang can you describe the spec of your browser? I remember he doesn't even use any sort of adblocker.

**Comment by dillzhang** [comment]
<img width="1243" alt="screen shot 2019-02-28 at 23 46 19" src="https://user-images.githubusercontent.com/7240621/53616966-23f5b200-3bb3-11e9-9ee5-18a557b145c8.png">
<img width="691" alt="screen shot 2019-02-28 at 23 46 32" src="https://user-images.githubusercontent.com/7240621/53616967-23f5b200-3bb3-11e9-812b-2b0ebd94d7a7.png">

Here is my chrome version and all the extensions I am running.
