### ISSUE TITLE
Add hyperlinks  and sidebar for docs

### ISSUE THREAD

**Issue by dillzhang** [soyapark/murmur#19]
The docs currently references to specific functions. Add these references and a sidebar to make navigating docs easier.

**Comment by soyapark** [comment]
I wish the left sidebar visualizes nested views clearly. 
![image](https://user-images.githubusercontent.com/33616044/53200734-48202480-35f0-11e9-943d-83ea1cda0312.png)
For example, for our API, there should be "Retrieve metadata of an email". Under this header, each get_*() should have some indentation.  

As for the hyperlink, when users hover over a header, users' mouse cursor is changed to a 'pointer' type and a hyperlink icon pops up next to the header. 

Good example: https://docs.python.org/3.4/library/datetime.html

**Comment by lukesmurray** [comment]
not sure if we want to do it but this type of sidebar is automatically generated by the markdown to html converter [mume](https://github.com/shd101wyy/mume/tree/master/src). It would mean our docs would have to be written in markdown though.

**Comment by dillzhang** [comment]
I think I can automate some of the sidebar generation with mavo similar to how we generate the docs.
