### ISSUE TITLE
Show imported library and its namespace to users at the interface

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#23]
We should expose which library is available to use. 
Per each editor, we can have a collapsible display and show namespace of each imported library.

**Comment by lukesmurray** [comment]
What type of library is this referring to? Are we referring to python libraries like `sklearn`?

**Comment by soyapark** [comment]
Generic python library that users might want to use! It appears like this:
![image](https://user-images.githubusercontent.com/33616044/53464705-49e74f00-3a19-11e9-862e-f139739d81f8.png)

![image](https://user-images.githubusercontent.com/33616044/53464685-3cca6000-3a19-11e9-98a4-b94e052deb3c.png)
