### ISSUE TITLE
Setup code for mailbot needs to be rewritten

### ISSUE THREAD

**Issue by lukesmurray** [soyapark/murmur#30]
This probably takes precedence or should be done at the same time as #14 
The current setup for running the user's code is not going to be as useful with messages and threads.

https://github.com/soyapark/murmur/blob/543cf5c3f4ae999fa07e83d6907d47755504a0a6/smtp_handler/management/commands/mailbot.py#L31-L40

**Comment by soyapark** [comment]
We will entirely abandon mailbot.py as we will transfer to use Celery and message arrival trigger. Current mailbot.py implementation doesn't support multithreading. I will talk to you about this in a meeting.

**Comment by lukesmurray** [comment]
this is done in #29
