### ISSUE TITLE
is_test

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#49]
I made this argument called `is_test` (boolean). Probably y'all wonder about what the heck is this.  
I made this to let users simulate their rules before they actually apply their rule. I haven't used this argument at my development that much, but I feel like we need to revive this arg. 

YoUPS interface has this switch to turn on and off this feature but no one gets what it does. Maybe we can add a button "Compile" next to "RUN".

**Comment by lukesmurray** [comment]
I'm confused about what Compile would mean.

**Comment by soyapark** [comment]
Then maybe "Simulate"?

**Comment by lukesmurray** [comment]
that definitely makes more sense. Test is like, does your code work. Simulate is more like we won't do anything.
