### ISSUE TITLE
Celery lock

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#52]
http://docs.celeryproject.org/en/latest/tutorials/task-cookbook.html#cookbook-task-serial

**Comment by lukesmurray** [comment]
this is exactly what we need. nice. The only thing we want to double check is that the lock applies to any access to the same account, including when the user runs their code manually or saves it etc.

**Comment by lukesmurray** [comment]
This is definitely high priority. I crash on every single new email and have pretty strong evidence that celery tasks are being duplicated.

**Comment by lukesmurray** [comment]
ok this appears to be working
