### ISSUE TITLE
no support for folder selection on modes

### ISSUE THREAD

**Issue by lukesmurray** [soyapark/murmur#56]
Users can select folders in the front end but it does nothing in the backend.

**Comment by soyapark** [comment]
I'm implementing this where users can check checkboxes per mode and save it to our database. 
You can implement a consuming part at your sync function by fetching values from [MailbotMode_Folder](https://github.com/soyapark/murmur/blob/3fcc09db2abdd3dce8de86b478cd95f3feb49745/schema/youps.py#L177) 

e.g., 
```
mode_folder = MailbotMode_Folder.objects.filter(imap_account=imap, mode=current_mode)
for mf in mode_folder:
   imap.select_folder(mf.name)
   interpret()
```

**Comment by soyapark** [comment]
UI part is ready https://github.com/soyapark/murmur/pull/65
