### ISSUE TITLE
Google analytics or any means to record users' activity

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#9]
Maybe not relying on google analytics is a good idea since many users might use adblock at their web browser.

**Comment by lukesmurray** [comment]
We could talk to Midas about the best way to request consent from users to track them. 

It looks like [approx 10% of users](https://www.quantable.com/analytics/how-many-users-block-google-analytics/) block Google Analytics and it is probably the easiest way to go about gathering user data.
